# Generated by Django 5.1.4 on 2025-02-27 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talkw", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="anonymous",
        ),
        migrations.DeleteModel(
            name="CustomUser2",
        ),
    ]
